FROM centos:latest
ENV container docker

RUN yum install -y man \
    && yum install -y openssh-server \
    && yum install -y unzip \
    && yum install -y initscripts \
    && yum install -y git \
    && yum install -y ctags \
    && yum install -y dos2unix \
    && yum install -y python-devel \
    && yum install -y gcc-c++ \
    && yum install -y make \
    && yum install -y cmake \ 
    && yum install -y ncurses-devel

ADD http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz https://pypi.python.org/packages/source/p/pip/pip-1.3.1.tar.gz /opt/
RUN tar xzvf /opt/setuptools-0.6c11.tar.gz -C /opt \
    && cd /opt/setuptools-0.6c11 \ 
    && python setup.py install \
    && tar -xzvf /opt/pip-1.3.1.tar.gz -C /opt \
    && cd /opt/pip-1.3.1 \
    && python setup.py install \
    && pip install autopep8

# install vim8
RUN mkdir -p /root/.vim/{autoload,bundle} 
ADD YouCompleteMe.tar.gz /root/.vim/bundle/
ADD vim8.tar.gz /opt/
RUN /opt/vim-master/src/configure  --with-features=huge -enable-pythoninterp  --with-python-config-dir=/usr/lib64/python2.7/config --enable-cscope --enable-multibyte \
    && make \
    && make install \
    && rm -rf /usr/bin/vi \
    && ln -s /usr/local/bin/vim /usr/bin/vi \
    && curl -LSso /root/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim \
    && /root/.vim/bundle/YouCompleteMe/install.py \
    && cp /root/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py /root/ \
    && cd /root/.vim/bundle/ \
    && git clone --depth 1 https://github.com/scrooloose/nerdtree \
    && git clone --depth 1 https://github.com/Yggdroot/indentLine \
    && git clone --depth 1 https://github.com/tell-k/vim-autopep8 \
    && git clone --depth 1 https://github.com/jiangmiao/auto-pairs \
    && git clone --depth 1 https://github.com/jlanzarotta/bufexplorer \
    && git clone --depth 1 https://github.com/plasticboy/vim-markdown \
    && git clone --depth 1 https://github.com/ekalinin/Dockerfile.vim \
    && git clone --depth 1 https://github.com/majutsushi/tagbar \
    && git clone --depth 1 https://github.com/scrooloose/syntastic \
    && git clone --depth 1 https://github.com/vim-scripts/taglist.vim \
    && git clone --depth 1 https://github.com/bling/vim-airline \
    && git clone --depth 1 https://github.com/vim-airline/vim-airline-themes \
    && git clone --depth 1 https://github.com/tpope/vim-surround \
    && git clone --depth 1 https://github.com/vim-scripts/indentpython.vim \
    && git clone --depth 1 https://github.com/tpope/vim-fugitive \
    && git clone --depth 1 https://github.com/flazz/vim-colorschemes \
    && git clone --depth 1 https://github.com/altercation/vim-colors-solarized \
    && git clone --depth 1 https://github.com/bronson/vim-trailing-whitespace \
    && git clone --depth 1 https://github.com/Glench/Vim-Jinja2-Syntax \
    && git clone --depth 1 https://github.com/elzr/vim-json

COPY vimrc /root/.vimrc
RUN dos2unix /root/.vimrc \

CMD ["/usr/sbin/init"]
