FROM tmux:latest
ENV container docker

#RUN mkdir -p  ~/.pip/ \
    #&& echo -e "[global]\nindex-url = http://mirrors.myhuaweicloud.com/pypi/web/simple\nformat=columns\n\n[install]\ntrusted-host = mirrors.myhuaweicloud.com" > ~/.pip/pip.conf  

RUN rm -rf /usr/bin/python \
    && pacman -S python3 --noconfirm \
    && pacman -S python-setuptools --noconfirm \
    && pacman -S python-wheel --noconfirm \
    && pacman -S python-pip --noconfirm \
    && echo -e "#! /bin/bash\nrm -rf /usr/bin/python\nln -s /usr/bin/python3 /usr/bin/python" > /usr/local/bin/chpy3 \
    && chmod +x /usr/local/bin/chpy3 \
    && /usr/local/bin/chpy3 \
    && rm /usr/lib/python3.12/EXTERNALLY-MANAGED 

COPY requirements.txt /root/
RUN pip3 install --no-cache-dir -r /root/requirements.txt 

# jupyter
RUN jupyter notebook --generate-config 
COPY config/jupyter/jupyter_notebook_config.py /root/.jupyter
COPY config/jupyter/jupyter.service /usr/lib/systemd/system  
# RUN jupyter contrib nbextension install --user --skip-running-check \
#     && echo "c.NotebookApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py \
#     && systemctl enable jupyter.service

# RUN pacman -S cloc --noconfirm 
