#docker run -dit --name my --hostname=lijian --privileged -p 23:22 -p 8888:8888 -p 9999:9999 -p 8080:8080 -p 7443:7443 -v /usr1:/usr1 -v /usr1/docker/mount/gitconfig:/root/.gitconfig -v /usr1/git-credentials:/root/.git-credentials -v /usr1/docker/mount/py_check:/root/py_check -v /usr1/docker/mount/zshrc.my:/root/.zshrc.my -v /usr1/docker/mount/zsh_history:/root/.zsh_history -v /usr1/docker/mount/resurrect:/root/.tmux/resurrect -v /usr1/docker/mount/pip.conf:/root/.pip/pip.conf -v /usr1/docker/mount/nvim:/root/.local/share/nvim -v /usr1/docker/mount/ssh:/root/.ssh/ --restart=always my:20210705

#docker network create --driver=bridge --subnet=172.19.0.0/16 my
# 宿主机的docker.sock挂载到/docker.sock，如果在容器内要使用需要创建软链接(ln -s /docker.sock /var/run/dock.sock)， 直接挂载到/var/run/docker.sock会失败(必须使用bash作为CMD才能成功)
TAG="20230727"
#TAG="20240206"
# 使用方法：先执行本脚本启动，然后再执行init.sh初始化

docker run -dit --name my --hostname=lijian --privileged --net my_net --ip 172.18.1.2 -p 8000:22 -p 8888:8888 -p 9999:9999 -p 8080:8080 -p 7443:7443 -p 8090:8090 -p 2181:2181 -p 80:80 -p 123:123 -p 20051:20051 -v /usr1/docker/mount/hosts:/etc/hosts -v /usr1/docker/mount/resolv.conf:/etc/resolv.conf -v /var/run/docker.sock:/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /usr1:/usr1 -v /share:/share --restart=always my:"${TAG}"

#docker run -dit --name my --hostname=lijian --privileged --net my --ip 172.19.1.2 -p 8000:22 -p 8888:8888 -p 9999:9999 -p 8080:8080 -p 7443:7443 -p 8090:8090 -p 2181:2181 -p 80:80 -p 123:123 -p 20051:20051 -p 30051:30051 -p 50051:50051 -p 60051:60051 -v /var/run/docker.sock:/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /usr1:/usr1 -v "${MOUNT_DIR}"/gitconfig:/root/.gitconfig -v "${MOUNT_DIR}"/py_check:/root/py_check -v "${MOUNT_DIR}"/zshrc.my:/root/.zshrc.my -v "${MOUNT_DIR}"/zsh_history:/root/.zsh_history -v "${MOUNT_DIR}"/resurrect:/root/.tmux/resurrect -v "${MOUNT_DIR}"/pip.conf:/root/.pip/pip.conf -v "${MOUNT_DIR}"/nvim:/root/.local/share/nvim -v "${MOUNT_DIR}"/TabNine:/root/.local/share/TabNine -v "${MOUNT_DIR}"/p10k.zsh:/root/.p10k.zsh -v "${MOUNT_DIR}"/cheat_personal:/root/.config/cheat/cheatsheets/personal -v "${MOUNT_DIR}"/pm/projects:/root/.pm/projects -v "${MOUNT_DIR}"/autojump:/root/.local/share/autojump -v "${MOUNT_DIR}"/ssh:/root/.ssh/ -v "${MOUNT_DIR}"/hosts:/etc/hosts -v "${MOUNT_DIR}"/obsutilconfig_hwcloud:/root/.obsutilconfig -v "${MOUNT_DIR}"/nginx.conf:/etc/nginx/nginx.conf -v /share:/share -v "${MOUNT_DIR}"/vim_tasks.ini:/root/.vim/tasks.ini -v "${MOUNT_DIR}"/ansible/hosts:/etc/ansible/hosts -v "${MOUNT_DIR}"/ansible/ansible.cfg:/etc/ansible/ansible.cfg -v "${MOUNT_DIR}"/settings.xml:/root/.m2/settings.xml -v "${MOUNT_DIR}"/java_check:/root/java_check -v "${MOUNT_DIR}"/fish/fish_history:/root/.local/share/fish/fish_history -v "${MOUNT_DIR}"/kube/:/root/.kube --restart=always my:"${TAG}"

# 如果想让jdt.ls快速加载，只能以/bin/bash启动

#docker run -dit --name my1 --hostname=lijian --privileged --net my -v /var/run/docker.sock:/docker.sock -v /usr/bin/docker:/usr/bin/docker -v /usr1:/usr1 -v /usr1/docker/mount/gitconfig:/root/.gitconfig -v /usr1/git-credentials:/root/.git-credentials -v /usr1/docker/mount/py_check:/root/py_check -v /usr1/docker/mount/resurrect:/root/.tmux/resurrect -v /usr1/docker/mount/pip.conf:/root/.pip/pip.conf -v /usr1/docker/mount/nvim:/root/.local/share/nvim  -v /usr1/docker/mount/cheat_personal:/root/.config/cheat/cheatsheets/personal -v /usr1/docker/mount/pm/projects:/root/.pm/projects -v /usr1/docker/mount/autojump:/root/.local/share/autojump -v /usr1/docker/mount/ssh:/root/.ssh/ -v /usr1/docker/mount/hosts:/etc/hosts -v /usr1/docker/mount/obsutilconfig_hwcloud:/root/.obsutilconfig -v /usr1/docker/mount/nginx.conf:/etc/nginx/nginx.conf -v /share:/share -v /usr1/docker/mount/vim_tasks.ini:/root/.vim/tasks.ini -v /usr1/ansible/hosts:/etc/ansible/hosts -v /usr1/ansible/ansible.cfg:/etc/ansible/ansible.cfg -v /usr1/docker/mount/settings.xml:/root/.m2/settings.xml --restart=always my:20220331_patch
