local Plug = require("vimplug")

Plug.begin("~/.vim/bundle/")

--vim.fn.source('/root/.vim/rc/ale.vim')
-- vim.api.nvim_command('source /root/.vim/rc/ale.vim')
-- vim.api.nvim_command('source /root/.vim/rc/vista.vim')
--vim.api.nvim_command('source /root/.vim/rc/coc.vim')
vim.api.nvim_command("source /root/.vim/rc/vim-floaterm.vim")
vim.api.nvim_command("source /root/.vim/rc/leaderf.vim")
-- vim.api.nvim_command('source /root/.vim/rc/vim-airline.vim')
-- vim.api.nvim_command('source /root/.vim/rc/buffers.vim')
-- vim.api.nvim_command('source /root/.vim/rc/bufexplorer.vim')
-- vim.api.nvim_command('source /root/.vim/rc/indentline.vim')
-- vim.api.nvim_command('source /root/.vim/rc/vim-signify.vim')
vim.api.nvim_command("source /root/.vim/rc/textobj.vim")
-- vim.api.nvim_command('source /root/.vim/rc/rainbow_parentheses.vim')
vim.api.nvim_command("source /root/.vim/rc/vim-fugitvie.vim")
-- vim.api.nvim_command('source /root/.vim/rc/vim-dirvish.vim')
-- vim.api.nvim_command('source /root/.vim/rc/tabs.vim')
-- vim.api.nvim_command('source /root/.vim/rc/defx.vim')
-- vim.api.nvim_command('source /root/.vim/rc/nerdcommenter.vim')
-- vim.api.nvim_command("source /root/.vim/rc/bookmarks.vim")
-- vim.api.nvim_command('source /root/.vim/rc/buffers.vim')
-- vim.api.nvim_command('source /root/.vim/rc/bufexplorer.vim')
vim.api.nvim_command("source /root/.vim/rc/interestingwords.vim")
vim.api.nvim_command("source /root/.vim/rc/cscope.vim")
-- vim.api.nvim_command('source /root/.vim/rc/rainbow_parentheses.vim')
-- vim.api.nvim_command('source /root/.vim/rc/vim-shebang.vim')
-- vim.api.nvim_command("source /root/.vim/rc/python-mode.vim")
-- vim.api.nvim_command('source /root/.vim/rc/surround.vim')
-- vim.api.nvim_command('source /root/.vim/rc/quickfix.vim')
-- vim.api.nvim_command('source /root/.vim/rc/vim-preview.vim')
vim.api.nvim_command("source /root/.vim/rc/pep8.vim")
vim.api.nvim_command("source /root/.vim/rc/gtags.vim")
vim.api.nvim_command("source /root/.vim/rc/cscope.vim")
vim.api.nvim_command("source /root/.vim/rc/gutentags.vim")
vim.api.nvim_command("source /root/.vim/rc/gutentags_plus.vim")
vim.api.nvim_command("source /root/.vim/rc/vista.vim")
-- vim.api.nvim_command("source /root/.vim/rc/gruvbox.vim")
-- vim.api.nvim_command("source /root/.vim/rc/colorschema.vim")
-- Plug 'liuchengxu/vista.vim'

Plug.ends()
